name: .NET Integration Tests with MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check MySQL service logs
      if: always()
      run: docker logs mysql
    - name: Set up MySQL
      run: |
        sleep 10  # Wait for 10 seconds before trying to connect
        mysql -h mysql -e 'SHOW DATABASES;' -uroot -p${{ env.MYSQL_ROOT_PASSWORD }}  # Test with SHOW DATABASES first
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run migration
      run: dotnet tool install --global dotnet-ef
    - name: Test
      run: dotnet test --no-build --verbosity normal
